# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'

defaults:
  run:
    working-directory: frontend

# Event for the workflow
on:
  push:
    branches:
      - 'form-v2/develop'
  pull_request:
    branches:
      # PR events to branches matching refs/heads/form-v2
      - 'form-v2'
      - 'form-v2/**'

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history with v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: npm ci --ignore-scripts
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: frontend
          onlyChanged: true
          # 👇 Do not need to wait for changes since Chromatic will report any updates.
          exitOnceUploaded: true
