name: CI (React)

defaults:
  run:
    working-directory: frontend

on:
  push:
    branches:
      # Push events to branches matching refs/heads/form-v2
      - 'form-v2'
      - 'form-v2/**'
  pull_request:
    branches:
      # PR events to branches matching refs/heads/form-v2
      - 'form-v2'
      - 'form-v2/**'
    types: [opened, reopened]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: npm ci
      - name: Run frontend unit tests
        run: npm test
      - name: Run frontend a11y tests
        run: npm run test:a11y
        # Set job to pass even if a11y tests fail.
        continue-on-error: true
